services:
  n8n:
    image: n8nio/n8n:1.112.6
    ports:
      - 5678:5678
    environment:
      WO_API_KEY: ${WO_API_KEY}
      SLACK_BOT_API_KEY: ${SLACK_BOT_API_KEY}
      N8N_BLOCK_ENV_ACCESS_IN_NODE: ${N8N_BLOCK_ENV_ACCESS_IN_NODE}
      N8N_HOST: ${SUBDOMAIN}.${DOMAIN_NAME}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      NODE_ENV: production
      OPONEO_EMAIL: ${OPONEO_EMAIL}
      N8N_RUNNERS_ENABLED: ${N8N_RUNNERS_ENABLED}
      OPONEO_PASSWORD: ${OPONEO_PASSWORD}
      WEBHOOK_URL: https://${SUBDOMAIN}.${DOMAIN_NAME}/
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${TZ}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
      - ./workflows:/home/node/workflows
  sync-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ipc: host
    init: true
    environment:
      OPONEO_LOGIN_URL: ${OPONEO_LOGIN_URL}
      OPONEO_RESERVATIONS_LIST_URL: ${OPONEO_RESERVATIONS_LIST_URL}
      OPONEO_BASE_URL: ${OPONEO_BASE_URL}
      PORT: ${PORT}
      WEBSHARE_ACCOUNT_1: ${WEBSHARE_ACCOUNT_1}
      WEBSHARE_ACCOUNT_2: ${WEBSHARE_ACCOUNT_2}
      WEBSHARE_ACCOUNT_3: ${WEBSHARE_ACCOUNT_3}
      WEBSHARE_ACCOUNT_4: ${WEBSHARE_ACCOUNT_4}
      WEBSHARE_ACCOUNT_5: ${WEBSHARE_ACCOUNT_5}
      PROXY_BLACKLIST: ${PROXY_BLACKLIST}
    volumes:
      - ./:/app/
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  n8n_data:
  redis_data:
